name: Build app and deploy docker

on:
  push:
    branches:
      - "test-cd"

jobs:
  push-to-docker:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo in order to fetch the latest content
      - name: Checkout repo
        uses: actions/checkout@v2
      # Login to ghcr
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      # Build the docker image now
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/deepjyoti30/blog-frontend:latest
      